# Generated by Django 2.2.5 on 2019-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostsPosts', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='boast',
            name='boastlikes',
            field=models.ManyToManyField(related_name='boastlikes', to='GhostsPosts.Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='postlikes',
            field=models.ManyToManyField(related_name='postlikes', to='GhostsPosts.Author'),
        ),
    ]
